# docker-compose.yml
services:
  web:
    build: .
    command: >
      sh -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/codev
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - EMAIL_HOST=${EMAIL_HOST}          
      - EMAIL_PORT=${EMAIL_PORT}          
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD} 
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: